### PR TITLE
Relax country gem dependency

### PR DESCRIPTION
**Pull request by gssbzn**
Country has now released version 3 https://github.com/hexorx/countries/releases/tag/v3.0.0

### CODE REVIEW

**Comment by kevin-jj** [comment]
It would be great to get it merged and roll out a new release. @scudco @stefanpenner

**Comment by scudco** [comment]
Thanks for opening this PR. I'd be happy to get this merged once we can resolve the following comments.

1. Why was Rails 3 support removed?
2. Why was Ruby <2.3 support removed?
3. Can you provide a reasonable justification for changing the `countries` gem dependency to `>=`? I find this kind of thing generally dangerous since `countries` is basically the heart of the `country_select` gem. I've generally released a new major version every time countries does the same.
4. If you're getting ruby errors around `VERSION` being unfrozen, I'd prefer `# frozen_string_literal: true` at the top of the `version.rb` file.

**Comment by gssbzn** [comment]
Countries had some issues with their latest releases, 2.2 was janked and
3.0 came in place which left some users (our company included) trying to
solve this dependency/version problem, specially as country select was
locking to 2.x then things like circleci or heroku started to fail
As I updated the the dependency I didn't want to update lock files for old
versions of rails that are end of life, there's no longer any kind of
support for rails before 4.2 and as I updated the Travis matrix I decided
to also remove old rubies, again there's no longer any kind of support for
any ruby before 2.3
Me removing old rails or rubies is just keeping up with what a lot of the
community is doing trying not to support versions that the core team is no
longer supporting as well

**Comment by gssbzn** [comment]
Also for clarification the breaking change in countries is that the money gem is not included or enabled by default now, which should not affect country select at all

**Comment by scudco** [comment]
Thanks for your quick responses @gssbzn 

### Unsupported ruby and rails versions
I'm not comfortable removing support for older ruby or rails versions if nothing is currently breaking. I prefer to maintain `country_select` as a utility gem that will work on as many rails deployments as possible _until_ some breaking change requires dropping support. The fact that older versions of both ruby and rails are no longer officially supported is a good one, but it currently costs very little to continue testing against these older versions. Regardless, if we'd like to remove support for older ruby and/or rails versions, then I'd prefer that be in a separate PR.

### Permissive version selector for `countries`
I do not see the bad release of `countries` 2.2 as a good enough reason to change how `country_select` tracks the `countries` gem. The implication of using `countries` `>= 2` means that `country_select` is susceptible to breaking whenever `countries` releases new major versions. Because this is a utility gem, I'd prefer to continue letting `country_select` specify the major version of `countries` it has been tested against.

Out of curiousity, if you had specified the last known good version of `countries` in your Gemfile (`2.1.4` from what I can tell), would your deploy problem have been resolvable? Were you in need of some new functionality in `2.2` that you were then unable to access once `3.0` was released?

**Comment by gssbzn** [comment]
@scudco I understand your concerns so I've focused this PR to only address the countries gem issue, in our particular case we just deleted the lockfile and regenerated it as we were comfortable just doing that, we never got issues deploying as circleci warned us about the issue before trying a deploy but some people have commented about it https://github.com/hexorx/countries/issues/556#issuecomment-448120179

Since countries follows a semver system I just locked the version to never install v4+ as v3 is still a safe version of the gem to use

If the project welcomes a separate PR to remove EOL versions of ruby or rails let me know and I can address that as well, I think at least dropping rails 3 should be welcomed as a file can be deleted and an `if` is no longer necessary, which helps on maintainability in general

**Comment by scudco** [comment]
I'm merging this, but I still plan on continuing to track the `country_select` major version against the `countries` major version. I considered supporting both versions, but the responsible thing to do in that case would be to add relevant gemfiles for countries 2 and 3. I don't want to multiply the travis tasks by two. The next version of `country_select` pushed to rubygems.org will be a new major version requiring `countries` `~>3.0`.

### actionpack
`actionpack` is set to 5+ as a _development dependency_ so that you can develop against the latest actionpack and run the specs via `bundle && bundle exec rspec` instead of running every gemfile configuration via `rake`.

**Pull request merged**
