### PR TITLE
Setting up support for 2.0 branch of countries (WIP)

### PR DESCRIPTION
**Pull request by rposborne**
We are working on improving some of the memory performance by bringing in only data that a repo needs.   This targets our prerelease gem, with the only change to the spec being setting the available locales on I18n so the new countries gem will autoload only those translations. 

This is a WIP as 2.0 is not yet released. I know this is one of the major that depends on our data set.

### CODE REVIEW

**Comment by scudco** [comment]
Just chiming in to say thanks for setting this up. I'm hoping to find some time to play with this branch next week.

**Comment by rposborne** [comment]
Just an FYI, 2.0 has been merged into our master.

**Comment by scudco** [comment]
thanks, going to take a look now.

**Comment by scudco** [comment]
Tests are looking good. I've got this on my own branch with the latest changes from `country_select` master using `countries` `2.0.0.pre.2`

I think we'll be ready to release a new point version once you release `2.0.0`

thanks again!

**Comment by rposborne** [comment]
Countries 2.0 has landed. This has been rebased and updated, please review :)

**Comment by scudco** [comment]
Thanks for keeping this PR up-to-date. I will get it merged and push a new release this weekend if everything looks good. Sorry can't do it sooner!

**Comment by scudco** [comment]
Does countries 2.0 still support older rubies, specifically 1.9.3? It appears travis is failing because 1.9.3's default encoding when reading files is `US-ASCII` and cannot load the new emoji file correctly.

Would you consider just adding the encoding to the top of that file with `#encoding: utf-8`? I have tried a few different ENV vars on the travis end to get the 1.9.3 build working, but no go.

On the other hand, if countries 2.0.0 is explicitly dropping support for Ruby 1.9, then I can update the countries build and README appropriately.

**Comment by rposborne** [comment]
@scudco I think we can say that we are going to explicitly drop 1.9.3 support, we are over a year out of support on 1.9.3 anyway.

**Comment by scudco** [comment]
Okay, I think you just need to rebase some of the commits and rebundle with the latest updates I've made to master. This should be good to go once the conflicts are resolved.

**Comment by Fudoshiki** [comment]
gem Countries 2.0.2 released

**Comment by Fudoshiki** [comment]
Any updates?

**Comment by scudco** [comment]
Made a rebased branch and merged it in #138

**Comment by scudco** [comment]
@rposborne @Fudoshiki I just pushed 3.0 up to rubygems

**Pull request closed without merging**
