### PR TITLE
Upgrade countries gem to 1.1.0

### PR DESCRIPTION
**Pull request by cbetta**

### CODE REVIEW

**Comment by scudco** [comment]
Looks good :)

I looked at the changelog for `countries` and didn't notice any big changes, but I'm curious, was there a specific change on `countries` that requires you to have `~> 1.1.0`?

**Comment by cbetta** [comment]
I just like to be up to date and these 2 gems tend to go hand in hand for me.

**Comment by scudco** [comment]
Cool, good to know :+1:

**Comment by scudco** [comment]
https://rubygems.org/gems/country_select/versions/2.4.0

Thanks again

**Comment by cbetta** [comment]
Awesome, cheers and no worry

**Pull request merged**
