### PR TITLE
Update countries gem

### PR DESCRIPTION
**Pull request by kirillplatonov**
Relates to #92

### CODE REVIEW

**Comment by scudco** [comment]
I think this is good, but do we have a reason to prefer `~> 0.11.0` over just going back to `>= 0.9.3`?

**Comment by kirillplatonov** [comment]
@scudco 0.10.1 not released, and if I understand correctly #92 0.10.0 has performance regression. So I think it's good idea to stick 0.11.

**Comment by scudco** [comment]
Oh, of course, we want to make sure no one gets stuck on `0.10.0`

Thanks.

**Comment by kirillplatonov** [comment]
@scudco Could you bump version on rubygems?

**Comment by scudco** [comment]
This is breaking quite a few tests after updating the Gemfiles https://travis-ci.org/stefanpenner/country_select/builds/54969076

Once I get these fixed, then I'll release `2.2.0`

**Pull request merged**
