### PR TITLE
Added country codes.

### LINKED ISSUE #142: country_select: how to add countries' attributes as HTML data?
Hello,

I'm using country select to populate a `select` field. When the user selects a country, I would like to set the value of another field, `telephone`, to the country code using JS.

For this to work, I would like to add a `data` attribute containing the country code to each `option` field. What I need is this:

`<option value="AT" data-code="43">`

Is is possible to set add a data attribute when calling `country_select`?

Thanks!

### PR DESCRIPTION
**Pull request by dcangulo**
Fixes #142

### CODE REVIEW

**Comment by scudco** [comment]
I think what would make this merge-able is if this were extracted to a general option. Choosing to include the telephone `country_code` should be an option rather than a default.

What I'd like to see is something like
```erb
<%= f.country_select :country_alpha2, include_data: ['country_code', 'alpha3'] %>
```
```html
<option value="GB" data-country-code="44" data-alpha3="GBR">United Kingdom</option>
```

This kind of approach could also lay the groundwork for how I probably _should've_ added ISO country codes to this gem in the first place by allowing a developer to specify the value and label through options.

```erb
<%= f.country_select :country_alpha3, option_value: :alpha3, option_text: :emoji_flag %>
```
```html
<option value="GBR">🇬🇧</option>
```

Do you think you'd be up for adapting this PR to implement something like the `include_data` option?

**Comment by dcangulo** [comment]
@scudco I really think my code is bad as I've only been coding RoR in the past 2 and a half months. Please guide me on how can I improve with this code.

**Comment by dcangulo** [comment]
```ruby
<%= f.country_select :country_code, include_data: ['country_code', 'alpha3'] %>
```
Will return:
```ruby
<option value="PH" data-country-code="63" data-alpha3="PHL">Philippines</option>
```
---
```ruby
<%= f.country_select :country_code, include_data: ['country_code'] %>
```
Will return:
```ruby
<option value="PH" data-country-code="63">Philippines</option>
```
---
```ruby
<%= f.country_select :country_code, include_data: ['alpha3'] %>
```
Will return:
```ruby
<option value="PH" data-alpha3="PHL">Philippines</option>
```

**Comment by scudco** [comment]
I'm really happy to see this with tests and everything. However, I feel really bad about having forgotten that there already exists a way to do this with custom formatters. It's a powerful, but poorly documented feature that allows you to define a block to format the `option` tag.

I've added some more detailed documentation to the demo app at https://country-select-test.herokuapp.com/ under the "Using a custom formatter" section. Let me know if that helps you or if you have any trouble implementing it.

I very much appreciate you taking the time to iterate on this and write tests. I'm leaving this PR open because I would think on this approach more. My feeling is that custom formatters are great, but are that they represent too steep a learning curve. I'd like to support more of these inline options like `include_data` so that there are more immediate, at-hand hooks for customizing `country_select`.

**Comment by scudco** [comment]
want to get some things changed to support better formatters, but I'm going to close this PR

**Pull request closed without merging**
