### PR TITLE
Fix value call on Rails edge (5.2+)

### PR DESCRIPTION
**Pull request by ybart**
https://github.com/rails/rails/pull/29791

### CODE REVIEW

**Comment by scudco** [comment]
Let me update the Gemfile in a separate PR so this has a smaller changeset.

**Comment by scudco** [comment]
@ybart Is there a test you can write that proves that something unexpected happens on ActionPack edge?  rails/rails#29791 was merged a couple weeks ago. Either #147 should have a failing test in Travis or we need to add one to catch this problem in the future.

**Comment by ybart** [comment]
@scudco I think #147 does not break because the revision for Rails in Edge lockfile is not updated to the latest. To update it, I had to remove the lockfile and regenerate it.

**Comment by scudco** [comment]
Okay, got it. I'll have to figure out the right way to make it always update `gemfiles/actionpack.edge.gemfile.lock`. Travis is running now with the latest.

**Comment by scudco** [comment]
Okay, can you just rebase this and use the latest in master?

**Comment by scudco** [comment]
I hope I can suggest a difference of approach here to avoid version checking.

Instead of reaching into the the `VERSION` constants, we can just test the arity of `value`. Something like 

```ruby
    def country_option_tags
      # In Rails 5.2+, `value` accepts no arguments and must also be called
      # called with parens to avoid the local variable of the same name
      # https://github.com/rails/rails/pull/29791
      selected_option = @options.fetch(:selected) do
        if self.method(:value).arity > 0
          value(@object)
        else
          value()
        end
      end

      option_tags_options = {
        :selected => selected_option,
        :disabled => @options[:disabled]
      }
      # ...
    end
```

Let me know what you think.

**Comment by scudco** [comment]
Though, I now realize that should be inverted.

```ruby
    def country_option_tags
      # In Rails 5.2+, `value` accepts no arguments and must also be called
      # called with parens to avoid the local variable of the same name
      # https://github.com/rails/rails/pull/29791
      selected_option = @options.fetch(:selected) do
        if self.method(:value).arity == 0
          value()
        else
          value(@object)
        end
      end

      option_tags_options = {
        :selected => selected_option,
        :disabled => @options[:disabled]
      }
      # ...
    end
```

**Comment by ybart** [comment]
That seems a good idea, let's try that.

**Comment by scudco** [comment]
Thanks for catching this and submitting a PR!

Once master turns green I'll push 3.1.1.

**Comment by scudco** [comment]
@ybart it's finally up, travis problems... https://rubygems.org/gems/country_select/versions/3.1.1

**Comment by ybart** [comment]
Great work. Thanks for the release!

**Pull request merged**
